//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDataLayer
{

    public partial class MemberOrderDetails
    {
        public int OrderId { get; set; }
        public string OrderText { get; set; }
        public int MemberId { get; set; }
    
        public virtual MemberLoginDetails MemberLoginDetails { get; set; }
    }
}
