//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLoginDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberLoginDetails()
        {
            this.MemberOrderDetails = new HashSet<MemberOrderDetails>();
        }
    
        public int MemberId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual MemberDetails MemberDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberOrderDetails> MemberOrderDetails { get; set; }
    }
}
